import { getSession } from 'next-auth/react'
import Head from 'next/head'
import Center from '../components/Center'
import Sidebar from '../components/Sidebar'


export default function Home() {
  return (
    <>
        <Head>
          <title>Spotify 2.0</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      <div className="bg-black h-screen overflow-hidden">
        <main className='flex'>
        <Sidebar/>
        <Center/>
        </main>
        <div></div>
      </div>

    </>
  )
}

export const getServerSideProps = async(context)=>{
  const session = await getSession(context)
  return{
    props:{
      session,
    }
  }
}